[package]
name = "sysinfo"
version = "0.1.0"
authors = ["Simon Tharby <jinjamail@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easycurses = "0.13.0"
